name: Cypress test while push

on: 

    pull_request:        
        branches:
            - stage   
 
jobs:    

    check-title:
      
      runs-on: ubuntu-latest

      steps:

        - name: Check the Pull Request title
          uses: deepakputhraya/action-pr-title@master
          with:
            allowed_prefixes: 'chore: dev => stage'

    trigger:

        needs: check-title
               
        runs-on: ubuntu-latest           
        
        steps:
          - name: Trigger Cypress Workflow
            run: |
              repo_owner="hal00010001"
              repo_name="testes-e2e-cypress"
              event_type="trigger-workflow"
              service="testes-e2e-cypress"
              version="1.0.0"
              echo "tolken ${{ secrets.SECRETPAT }}"
              curl -L \
                  -X POST \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: Bearer ${{ secrets.SECRETPAT }}" \
                  -H "X-Github-Api-Version: 2022-11-28" \
                  https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
                  -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"service\": \"$service\", \"version\": \"$version\"} }"
       
            
            # - name: Invoke workflow in another repo
            #   uses: aurelien-baudet/workflow-dispatch@v2
            #   with:
            #     workflow: develop.yml
            #     # repo: hal00010001/testes-e2e-cypress
            #     repo: suflex-co/foodcamp-e2e
            #     ref: refs/heads/main
            #     token: ${{ secrets.SECRETPAT }}


        
        
          

        

    
