name: Cypress test while push

on: 
    push:
        branches:
            - stage       

jobs:
    trigger:
        runs-on: ubuntu-latest

        steps:
            - name: Trigger Cypress Workflow
              run: |
                repo_owner="hal00010001"
                repo_name="testes-e2e-cypress"
                event_type="trigger-workflow"
                service="testes-e2e-cypress"
                version="1.0.0"                
                curl -L \
                    -X POST \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: Bearer ${{ secrets.SECRETPAT }}" \
                    -H "X-Github-Api-Version: 2022-11-28" \
                    https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
                    -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"service\": \"$service\", \"version\": \"$version\"}, \"wait_workflow\": true }"
    
