name: Cypress test while push

on: 

    pull_request:        
        branches:
            - stage   
 
jobs:    

    check-title:
      
      runs-on: ubuntu-latest

      steps:

        - name: Check the Pull Request title
          uses: deepakputhraya/action-pr-title@master
          with:
            allowed_prefixes: 'chore: dev => stage'

    trigger:

        needs: check-title
               
        runs-on: ubuntu-latest           
        
        steps:   
          - name: Invoke workflow in another repo with inputs
            uses: benc-uk/workflow-dispatch@v1
            with:
             workflow: develop.yml
             repo: hal00010001/testes-e2e-cypress                    
             token: "${{ secrets.SECRETPAT }}"
             ref: refs/heads/main

            # - name: Invoke workflow in another repo
            #   uses: aurelien-baudet/workflow-dispatch@v2
            #   with:
            #     workflow: develop.yml
            #     repo: hal00010001/testes-e2e-cypress
            #     # repo: suflex-co/foodcamp-e2e
            #     ref: refs/heads/main
            #     token: ${{ secrets.SECRETPAT }}


        
        
          

        

    
